Title = "商城"

[Casdoor]
Endpoint = "http://localhost:8000"
GrantType = "authorization_code"
ClientId = "27a7d6599cbd78f0e666"
ClientSecret = "b9abe2f32b74f4268e57061334a639154b08a4b2"
Certificate = "./certs/token_jwt_key.pem"
OrganizationName = "echo_music"
ApplicationName = "shop"
RedirectUri = "http://localhost:3000/signin"
